const API='http://localhost:8080';
const token=sessionStorage.getItem('wonderos_token');
if(!token) location.href='./login.html';
const state={claim:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,...options.headers}});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Request failed');return j.data;}
function statuses(){return [...document.querySelectorAll('.queue-filters input:checked')].map(x=>x.value).join(',');}
async function loadQueue(){try{const rows=await api('/v1/claim-review-queue?statuses='+encodeURIComponent(statuses()));$('#queue').innerHTML=rows.length?rows.map(r=>`<button class="queue-item" data-id="${esc(r.wonder_id)}"><span class="status ${esc(r.status)}">${esc(r.status)}</span><strong>${esc(r.statement)}</strong><small>${esc(r.entity_name)} · ${esc(r.wonder_id)} · ${esc(r.evidence_count)} evidence</small></button>`).join(''):'<p class="muted">Nothing is waiting in this queue.</p>';document.querySelectorAll('.queue-item').forEach(b=>b.onclick=()=>openClaim(b.dataset.id));}catch(e){$('#queue').innerHTML=`<p class="form-error">${esc(e.message)}</p>`;}}
async function openClaim(id){try{const [claim,evidence,history]=await Promise.all([api('/v1/claims/'+id),api('/v1/claims/'+id+'/evidence'),api('/v1/claims/'+id+'/revisions')]);state.claim=claim;$('#empty').hidden=true;$('#workspace').hidden=false;$('#claim-id').textContent=claim.wonder_id;$('#entity').textContent=claim.entity_wonder_id;$('#status').textContent=claim.status;$('#status').className='status '+claim.status;$('#statement').value=claim.statement;$('#claim-type').value=claim.claim_type;$('#confidence').value=claim.confidence;$('#note').value='';$('#evidence').innerHTML=evidence.length?evidence.map(e=>`<article><strong>${esc(e.source_title)}</strong><span>${esc(e.stance)} · strength ${esc(e.strength)}</span><p>${esc(e.excerpt||e.locator||'No excerpt supplied.')}</p></article>`).join(''):'<p class="muted">No evidence has been linked yet.</p>';$('#history').innerHTML=history.length?history.map(h=>`<article><strong>Revision ${esc(h.revision)} · ${esc(h.status)}</strong><span>${esc(h.changed_by_name||h.changed_by_email||'Unknown editor')}</span><p>${esc(h.statement)}</p><small>${esc(h.change_note||'No note')}</small></article>`).join(''):'<p class="muted">No earlier revisions.</p>';}catch(e){show(e.message);}}
function show(message){$('#message').hidden=false;$('#message').textContent=message;}
async function mutate(status=null){if(!state.claim)return;$('#message').hidden=true;const body={expected_revision:Number(state.claim.revision),statement:$('#statement').value,claim_type:$('#claim-type').value,confidence:Number($('#confidence').value),change_note:$('#note').value};let path='/v1/claims/'+state.claim.wonder_id,method='PUT';if(status){path+='/review';method='POST';body.status=status;}try{const claim=await api(path,{method,body:JSON.stringify(body)});state.claim=claim;await openClaim(claim.wonder_id);await loadQueue();}catch(e){show(e.message);}}
$('#refresh').onclick=loadQueue;document.querySelectorAll('.queue-filters input').forEach(x=>x.onchange=loadQueue);document.querySelectorAll('.decision').forEach(b=>b.onclick=()=>mutate(b.dataset.status));$('#save').onclick=()=>mutate();loadQueue();
